config traefik 'config'
	# Whether to start Traefik on boot
	option enabled '1'
	
	# Log Traefik output to syslos
	option log_stderr '1'
	option log_stdout '1'

	# Traefik static configuration file
	option config_file '/etc/traefik/config.yml'